### ISSUE TITLE
Custom layer operations

### ISSUE THREAD

**Issue by Sanidhya27** [quic/aimet#1678]
Hi, I have a model with a custom layer which has 4 conv layers as its part and some other add subtract multiply and concat operations as part of forward function. Seems, torch.model  contains only layer information and not all nodes as in onnx. Also it seems aimet quantsim works only with layers and not individual operartions. So i cant observe effect of quantisation on those smaller operator nodes(especially concat which has inputs of different ranges).

Do we have a solution for this

**Comment by quic-akhobare** [comment]
@Sanidhya27 - Good observation. And yes.

So, PyTorch models unfortunately implement some layers as functionals. Unfortunate because for a tool like AIMET, it becomes difficult to simulate quantization for these layers.

For this we created the AIMET model preparer which will replace these functions with modules instead. Follow the code example here https://github.com/quic/aimet/blob/develop/Examples/torch/quantization/qat.ipynb. 

Specifically look for this code snippet

```
from aimet_torch.model_preparer import prepare_model
model = prepare_model(model)

```
The above example is for QAT. But you can stop when you see how the model is prepared, then the QuantizationSimModel is created and used for running quantized evaluations.
