### ISSUE TITLE
How is the bias parameters quantized?

### ISSUE THREAD

**Issue by jasonlovescoding** [quic/aimet#171]
Hi, I noticed the exported .encodings file contains quantization parameters for activation and weight. 
I'm curious how is bias parameters processed? In the quantization simulation, are they computed as original and unquantized, or do they also go through the quant-dequant process with the same quantization parameter as the weights?

Thanks!

**Comment by quic-ssiddego** [comment]
Hi @jasonlovescoding By default, quantization sim for bias parameters is disabled. This is the default setting because the targets we have tested with generally use 32-bit integer biases which is equivalent to FP32 from a quantization noise perspective. 
Having said that, AIMET does allow the users to override this behavior by passing in an appropriate config file to the QuantizationSim API. 
An example config file is available here:
https://github.com/quic/aimet/blob/develop/TrainingExtensions/common/src/python/aimet_common/quantsim_config/default_config.json
One could enable bias quantization using :
"params": 
{
     "bias": 
     {
         "is_quantized": "**True**"
      }
}
