### ISSUE TITLE
Add working example for compressing a PyTorch resnet18 model using Channel Pruning

### ISSUE THREAD

**Issue by quic-akhobare** [quic/aimet#345]
- Create a new examples directory at the top-level
- Use the API doc examples to apply Channel Pruning model compression to a PyTorch resnet18 model

If you are interested in working on this issue - please indicate via a comment on this issue. It should be possible for us to pair you up with an existing contributor to help you get started.

From a complexity perspective, this ticket is at an easy level.

**Comment by adityakoolkarni** [comment]
@quic-akhobare, I'm interested in working on this. I have some understanding of Channel Pruning.

**Comment by quic-akhobare** [comment]
@adityakoolkarni - excellent. Please go ahead. I saw that you also expressed interest in working on spatial svd example. I would suggest start with that first.

**Comment by adityakoolkarni** [comment]
Great! Got it.

**Comment by bluesky314** [comment]
@quic-akhobare i have a good understanding of this topic and have been playing with the library recently. Would be interested to work on this issue

**Comment by quic-akhobare** [comment]
Great to hear @bluesky314. Please go ahead. I will assign the ticket to you.

@adityakoolkarni - hope you are ok with this. There are several areas we can use help with on AIMET. More help the better.

**Comment by adityakoolkarni** [comment]
Sure! Happy to have more collaboration!

**Comment by bluesky314** [comment]
Awesome! Thanks @adityakoolkarni. Would be great to collaborate on this.

**Comment by bluesky314** [comment]
@quic-akhobare Is there any particular template we are supposed to follow like the video tutorial on the topic or can we structure it the way we like?

**Comment by quic-akhobare** [comment]
@bluesky314 - To be honest, we can take new ideas here. So please do what feels right to you. We can always refactor later.

Not to bias you but there might be some merit to enabling via a jupyter notebook or equivalent.

**Comment by bluesky314** [comment]
@quic-akhobare would like some clarity on how residual or concat connections are handled in winnowing. The doc says "Note that the presence of skip-connections or residuals sometimes prevents upstream layers from getting output-pruned.", does this mean that prunning or correct winnowing is not done in these cases?

Also how does aimnet know the layer dependencies, does it create a graph with a dummy input or such? Some detail on that would be nice to include as it seems missing from the docs.

Also is there any reference for Weight Reconstruction method used? The diagram indicates it is being done with the input and output of the original and compressed model. Shouldn't it be matching the outputs of both so that layer output is in the same range as before?

**Comment by bluesky314** [comment]
Also is there any reference for the Weight Reconstruction technique used?

**Comment by bluesky314** [comment]
Hey, @quic-akhobare  got the answer for the first case, that a downsampling operator is used but not the other do. Would you have any pointers to share?

**Comment by quic-akhobare** [comment]
@quic-sundarr  - could you please answer questions from @bluesky314

**Comment by quic-sundarr** [comment]
@bluesky314 
Here are the response to your questions.

>>> would like some clarity on how residual or concat connections are handled in winnowing
For Residuals followed by Add and Concat Ops, where there is a mismatch of channels, we use DownsamleLayer and UpsampleLayer,  as needed.


>>>  The doc says "Note that the presence of skip-connections or residuals sometimes prevents upstream layers from getting output-pruned.", does this mean that prunning or correct winnowing is not done in these cases?
For some models, it is possible that AIMET decides not to perform channel pruning for certain set of Ops in the model because of complexity and overhead. This doesn’t mean incorrect channel pruning or winnowing.  The returned model is always a working model. We continuously look for ways to keep improving Channel Pruning and Winnowing optimizations.


>>> Also how does aimnet know the layer dependencies, does it create a graph with a dummy input or such? Some detail on that would be nice to include as it seems missing from the docs.
Yes.  AIMET creates a graph with dummy inputs to understand layer dependencies. 

>>> Also is there any reference for Weight Reconstruction method used? The diagram indicates it is being done with the input and output of the original and compressed model. Shouldn't it be matching the outputs of both so that layer output is in the same range as before?
AIMET performs Linear regression fit between the original layer’s output and compressed layer’s input. Please refer the following description in the documentation  --> **“AIMET then performs linear regression to adjust the layer parameters.”** The diagram also indicates Linear Regression. Please note that the outputs won’t exactly match.  Channel Pruning does cause some drop in accuracy but it would be very minimal.

If you think some area of documentation is not clear, we invite you to update the documentation and send us a Pull Request.

Thanks for using AIMET and asking these questions.

**Comment by quic-sundarr** [comment]
@bluesky314 
Here are the response to your questions.

>>> would like some clarity on how residual or concat connections are handled in winnowing
For Residuals followed by Add and Concat Ops, where there is a mismatch of channels, we use DownsamleLayer and UpsampleLayer as needed.


>>>  The doc says "Note that the presence of skip-connections or residuals sometimes prevents upstream layers from getting output-pruned.", does this mean that prunning or correct winnowing is not done in these cases?
For some models, it is possible that AIMET decides not to perform channel pruning for certain set of Ops in the model. 
This doesn’t mean incorrect channel pruning or winnowing.  The returned model is always a working model. We continuously look for ways to keep improving Channel Pruning and Winnowing optimizations.


>>> Also how does aimnet know the layer dependencies, does it create a graph with a dummy input or such? Some detail on that would be nice to include as it seems missing from the docs.
Yes.  AIMET creates a graph with dummy inputs to understand layer dependencies. 

>>> Also is there any reference for Weight Reconstruction method used? The diagram indicates it is being done with the input and output of the original and compressed model. Shouldn't it be matching the outputs of both so that layer output is in the same range as before?
AIMET performs Linear regression fit between the original layer’s output and compressed layer’s input. Please refer the following description in the documentation  --> **“AIMET then performs linear regression to adjust the layer parameters.”** The diagram also indicates Linear Regression. Please note that the outputs won’t exactly match.  Channel Pruning does cause some drop in accuracy but it would be very minimal.

If you think some area of documentation is not clear, we invite you to update the documentation and send us a Pull Request.

Thanks for using AIMET and asking these questions.

**Comment by quic-ssiddego** [comment]
@adityakoolkarni @bluesky314 Just wanted to follow-up on this. Please let us know if you have further questions on this or require help with merging your updates. Look forward to your contributions to AIMET. Thank you!

**Comment by quic-akhobare** [comment]
There is an existing example now. Closing the ticket.
