### ISSUE TITLE
No Conv2d layers supported for dilation other than (1, 1)

### ISSUE THREAD

**Issue by bluesky314** [quic/aimet#439]
Was trying to do channel prunning on a model with different dialtion rates but got the error:
`AssertionError: No Conv2d layers supported for dilation other than (1, 1)`

Is there any way to bypass this? Why would this be an issue for the current pruning implementation? Would'nt pruning of different dilation rates be identical?

**Comment by quic-ssiddego** [comment]
@quic-sundarr could you please take a look at this query. Thank you.

**Comment by quic-sundarr** [comment]
@bluesky314

As of now, we are not supporting dilation other than (1,1) due to additional complexity during sampling and reconstruction.

You can bypass this by creating a modules_to_ignore list and passing it in auto_params  for the channel pruning API.

Add all the conv layers with dilation other than (1,1) to the following list:
<<< Code Snippet >>>
modules_to_ignore = [layer 1, layer2]
auto_params = ChannelPruningParameters.AutoModeParams(greedy_params,
                                                              modules_to_ignore=modules_to_ignore)
<<< End of code snippet >>>
                  

Please refer "Compressing using Channel Pruning in auto mode" code example here: 
https://quic.github.io/aimet-pages/AimetDocs/api_docs/torch_compress.html

**Comment by quic-akhobare** [comment]
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
