### ISSUE TITLE
Fix to help with libpymo dependency resolution

### ISSUE THREAD

**Issue by quic-ssiddego** [quic/aimet#497]

**Comment by badrid75** [comment]
Hi,  
What is the safe version to pick with this fix please ? I had encountered both, the python version and pymo as well when trying with Collab..
thanks
Badri

**Comment by quic-bharathr** [comment]
Hi @badrid75 could please use [version 1.14.0](https://github.com/quic/aimet/releases/tag/1.14.0) for now? We're working on updating the instructions for the latest 1.16.0 release. Also the use of Code Colab is currently broken since they moved to python 3.7 and our software was built for python 3.6. We're working on a solution for this as well. See also #275 and #496 for details.

**Comment by Silk760** [comment]
> Hi @badrid75 could please use [version 1.14.0](https://github.com/quic/aimet/releases/tag/1.14.0) for now? We're working on updating the instructions for the latest 1.16.0 release. Also the use of Code Colab is currently broken since they moved to python 3.7 and our software was built for python 3.6. We're working on a solution for this as well. See also #275 and #496 for details.

Since April you are looking !
