### ISSUE TITLE
Keras model / TF2.x support

### ISSUE THREAD

**Issue by kgvillan** [quic/aimet#656]
Hello collaborators,

Just a quick question: is there any planned updates to have AIMET compatible with Tensorflow 2.x?

Thank you,

**Comment by quic-ssiddego** [comment]
Hi @kgvillan Thank you for your query. Yes, we are working on updating AIMET to be compatible with TF 2.x.

**Comment by kgvillan** [comment]
Hi @quic-ssiddego Thank you for the response. Is there an ETA for this update (e.g. Q3 2021)?

**Comment by quic-akhobare** [comment]
> Hi @quic-ssiddego Thank you for the response. Is there an ETA for this update (e.g. Q3 2021)?

I am not sure we can commit to an ETA at the moment. But hope to be done with this by Q3.

**Comment by ice-tong** [comment]
Hi, is AIMET compatible with Tensorflow 2.x now(2022Q1) ?

**Comment by quic-ssiddego** [comment]
@ice-tong It is planned to be supported soon. Please watch this space for more updates.

**Comment by jasonw247** [comment]
Hello, is there a new ETA for TF 2.x support?

**Comment by tc-wolf** [comment]
I'm also interested, since it looks like in some of the [examples](https://github.com/quic/aimet/blob/develop/Examples/tensorflow/quantization/keras/keras_transformer_qat.ipynb) use Keras models without the sessions-based API, but the Tensorflow [adaround](https://github.com/quic/aimet/blob/develop/Examples/tensorflow/quantization/adaround.ipynb) and other examples use

```python
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
```
and the TF 1 APIs.

I notice that the https://quic.github.io/aimet-pages/releases/1.23.0/api_docs/tensorflow_quantsim.html#aimet_tensorflow.quantsim.QuantizationSimModel takes TF 1 sessions, while https://quic.github.io/aimet-pages/releases/1.23.0/api_docs/keras_quantsim.html#aimet_tensorflow.keras.quantsim.QuantizationSimModel takes a functional API (?) Keras model.

**Comment by quic-akhobare** [comment]
Hi @jasonw247  and @tc-wolf 

Good news is that TF 2.4 is now supported. There are two separate APIs. If you have a Keras model and a Keras eval pipeline and a Keras training pipeline - please use the APIs under aimet_tensorflow.keras. Please see docs for this here -https://quic.github.io/aimet-pages/releases/latest/api_docs/keras_quantization.html

Alternately if your training pipeline and eval pipeline use tensorflow sessions (in other words, your training/eval pipelines are at the lower TF level), then you can use the AIMET TensorFlow APIs. Please see docs for this here - https://quic.github.io/aimet-pages/releases/latest/api_docs/tensorflow_quantization.html

Let us know if you have any questions. Please close the ticket if you don't have any immediate questions.

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue. Thank you.
