### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute 'modules'

### ISSUE THREAD

**Issue by DavideA** [quic/aimet#662]
Hello,

I am trying to compress a Faster-RCNN detection model with channel pruning.

However, in the winnowing stage, called with the function `aimet_torch.winnow.winnow.winnow_model` I get the following exception:
````
File "/usr/local/lib/python3.6/dist-packages/aimet_torch/winnow/winnow.py", line 70, in winnow_model
    in_place, verbose)
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/winnow/mask_propagation_winnower.py", line 98, in __init__
    self._graph = ConnectedGraph(self._model, (dummy_input,))
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/meta/connectedgraph.py", line 202, in __init__
    self._construct_graph(model, model_input)
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/meta/connectedgraph.py", line 312, in _construct_graph
    self._parse_trace_graph(model, model_input, module_tensor_tuples_map)
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/meta/connectedgraph.py", line 361, in _parse_trace_graph
    if not is_leaf_module(subgraph_model):
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/utils.py", line 199, in is_leaf_module
    module_list = list(module.modules())
AttributeError: 'Parameter' object has no attribute 'modules'
````

Apparently, one of the parameters of the models (the weight of the first convolution in the ResNet stem)  is interpreted as a module and enters the `is_leaf_module` in line 361 in `aimet_torch/meta/connectedgraph.py`.

Here are my versions of Aimet and torch:
````
Aimet==1.10.0.0.100.0.486
AimetCommon==1.10.0.0.100.0.486
AimetTorch==1.10.0.0.100.0.486
torch==1.3.1+cu100
````

How can I solve this?
Thank you,
D

**Comment by quic-ssiddego** [comment]
@DavideA  Thank you for reporting this. @quic-klhsieh @quic-sundarr Could you please take a look at this.

**Comment by quic-klhsieh** [comment]
Hi @DavideA ,

For context, in this section of code, we are attempting to build our own internal representation of the Pytorch graph which is what we refer to as Connected Graph. As a part of this, we make use of Pytorch's jit trace to provide us a graph to parse.

In the graph, we typically see various types of nodes giving us module and connectivity information, including GetAttr nodes which define modules (which could in turn contain submodules), and Callmethod nodes which show how the GetAttr nodes are being called.

It looks like in your case, the subgraph_model in the stack trace came from a GetAttr node, but holds a parameter instead of a torch.nn.Module. It is unclear what would lead to this, it would help if you could provide the model definition of the module that the parameter is in, so we can attempt to reproduce the issue.

Also, if you wanted to try getting past the issue, I would first try adding a check after subgraph_model has been defined a few lines above, to continue on to the next node if subgraph_model is not of type torch.nn.Module.

**Comment by DavideA** [comment]
Hi,
and thank you for your answer.

The model I am winnowing is a Resnet18 from `torchvision.models.resnet18()`. It should be a pretty neat model definition, that is why I was thinking the problem is in incompatibilities between Aimet version and torch version. Could you please confirm the versions I reported are good to use in conjunction?

Also, the input to that winnow_model function is as follows:
````
model=ResNet (from torchvision)
input_shape=[1,3,600,1000]
list_of_modules_to_winnow=[(Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False), [0, 2, 3, 4, 5, 6, 11, 12, 15, 17, 19, 21, 23, 24, 25, 26, 27, 31, 33, 34, 35, 38, 39, 41, 43, 45, 53, 55, 56, 59, 60, 63])]
reshape=False
````

The parameter mistakenly interpreted as module is an `nn.Parameter`, shaped 64, 3, 7, 7, so it seems to me the first ResNet convolution (stem).

Thanks for help, 
D

**Comment by DavideA** [comment]
Hello, 

closing this as upgrading torch version fixed it.
````
Aimet==1.10.0.0.100.0.486
AimetCommon==1.10.0.0.100.0.486
AimetTorch==1.10.0.0.100.0.486
torch==1.4.0+cu100
torchvision==0.5.0+cu100
````

Best,
D

**Comment by quic-klhsieh** [comment]
Thanks for trying out the pytorch upgrade @DavideA, and apologies for not responding sooner regarding the versions.
It looks like you are also using an old version of AIMET, and so I would suggest upgrading to our latest 1.16.2 release. That way if you run into any more issues, it will be easier for us to debug.
