### ISSUE TITLE
First conv2d layer can not be pruned

### ISSUE THREAD

**Issue by TingfengTang** [quic/aimet#774]
Hi,
Prunning the first conv layer which follows the input(my input channel is 1) is not allowed by the  toolbox, the error is caused by the following line in function select_channels_to_prune:
all_indices = list(range(num_in_channels))

Is the first layer must be ignored when setting the parameters:
     auto_params = aimet_torch.defs.ChannelPruningParameters.AutoModeParams(greedy_params,
                                                                           modules_to_ignore=[...])
Thanks.

**Comment by LLNLanLeN** [comment]
@TingfengTang Hey, I believe so. According to the video tutorial which you can find in the github repo, the first conv shouldn't be pruned for Channel Pruning. The reason for that I believe is if the # of channels changed for the first convolution, there's a chance it'll affect the input as well (let say before pruning, input 3 channels is fine, but after pruning, input MUST be 2 channels). Then technically, it's changing the way the nature of the DL models, hence the first conv should be avoid from channel pruning.

**Comment by TingfengTang** [comment]
@LLNLanLeN 
Hi, what I mean is that, if the input size is 1*1*28*28, the first conv layer is 15*1*3*3, what I want to reduce is the output channel of the conv layer(the filter number applied to the input). I hope the first conv layer will be reduded to 6*1*3*3(15->5).

**Comment by TingfengTang** [comment]
@LLNLanLeN
Hi, what I mean is that, if the input size is 1x1x28x28 and the first conv layer is 15x1x3x3, what I want to reduce is the output channel of the conv layer(the filter number applied to the input). I hope the first conv layer will be reduded to 6x1x3x3(15->5).

**Comment by LLNLanLeN** [comment]
@TingfengTang I understand your point, but I believe the logic behind the error is that, there's a chance that it might reduce the conv layer to `6 x 0 x 3 x3` as well, and this might force the input to have 0 channels (instead of 1) and it's changing the model in a fundamental way. 

I was confused as well until I went through the tutorial video:

https://www.youtube.com/watch?v=zgfy57saqsQ&t=1019s&ab_channel=QualcommInnovationCenter 

it's explained at 17:00. I agree that we should be able to prune the first convolution layer without effect the output, and perhaps the best way to do this is to switch to Manual Mode instead of Auto. I think as long as we use Auto, pruning the first layer may not be possible.

**Comment by TingfengTang** [comment]
@LLNLanLeN I see,the fundamental difference is filter pruning v.s. channel pruning, the two concepts can easily get confused.

**Comment by quic-ssiddego** [comment]
Hi @TingfengTang  and @LLNLanLeN Just wanted to add to your conversation above : "perhaps the best way to do this is to switch to Manual Mode instead of Auto. I think as long as we use Auto, pruning the first layer may not be possible." Even if you change from auto to manual, first layer should be output channel pruned - you should skip input prune always.

**Comment by LLNLanLeN** [comment]
@quic-ssiddego thank you, that's actually very helpful. I haven't tried that approach yet, but now I know I shouldn't

**Comment by quic-hitameht** [comment]
Mark this issue as resolved. If you have any further question feel free to re-open or create a new issue.
